name: Changelog

on:
  push:
    branches:
      - master
      - '**'

jobs:
  create_changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: heinrichreimer/action-github-changelog-generator@v2.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

