name: Changelog

on:
  push:
    branches:
      - master
      - '**'

jobs:
  create_changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Generate Changelog
      uses: heinrichreimer/action-github-changelog-generator@v2.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        sinceTag: v0.57.0
    - name: Update Changelog
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -sam "Update Changelog"
          git push

