name: Electron

on:
  push:
    branches:
      - master
      - '**'

jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - name: npm install, lint, build, and test
      run: |
        npm ci
        npm run lint
        npm test
        npm run build
      env:
        CI: true
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - name: npm install, and build
      continue-on-error: true
      run: |
        npm ci
        npm run build
      env:
        CI: true
    - name: npm lint, and test
      continue-on-error: true
      run: |
        npm run lint
        npm test
      env:
        CI: true
  build_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - name: npm install, lint, build, and test
      run: |
        npm ci
        npm run lint
        npm test
        npm run build
      env:
        CI: true
